django-todo/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView

from todo.forms import CustomAuthForm
from todo.views import UserSignupView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LoginView.as_view(authentication_form=CustomAuthForm), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', UserSignupView.as_view(), name='signup'),
    path('todo/', include('todo.urls')),
]

django-todo/todo/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'todo'
urlpatterns = [
    path('', login_required(views.ItemView.as_view()), name='index'),
    path('update/<int:pk>/', login_required(views.ItemUpdateView.as_view()), name='update'),
    path('delete/<int:pk>/', login_required(views.ItemDeleteView.as_view()), name='delete'),
]

django-todo/todo/models.py
from django.db import models
from django.contrib.auth import get_user_model

# Create your models here.
class Item(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    text = models.CharField(max_length=128)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-date']

    def __str__(self):
        return self.text[:15] + '...'

django-todo/todo/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.utils.translation import gettext_lazy as _

from .models import Item

class CustomSignupForm(UserCreationForm):
    username = forms.CharField(label=_('Имя пользователя'), widget=forms.widgets.TextInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(label=_('Пароль'), strip=False, widget=forms.widgets.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label=_('Подтвержение пароля'), strip=False, widget=forms.widgets.PasswordInput(attrs={'class': 'form-control'}))

class CustomAuthForm(AuthenticationForm):
    username = forms.CharField(label=_('Имя пользователя'), widget=forms.widgets.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label=_('Пароль'), strip=False, widget=forms.widgets.PasswordInput(attrs={'class': 'form-control'}))

class ItemForm(forms.ModelForm):
    text = forms.CharField(widget=forms.widgets.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите предмет'}))
    class Meta:
        model = Item
        fields = 'text',

django-todo/todo/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import View
from django.views.generic.edit import UpdateView, DeleteView
from django.views.generic.base import ContextMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .models import Item
from .forms import ItemForm, CustomSignupForm


# TODO: learn how to write a mixin
# class AllowControlMixin:
#     def dispatch(self, request, *args, **kwargs):
#         obj = Item.objects.get(pk=kwargs['pk'])
#         if request.user.id == obj.user.id:
#             return View.dispatch(self, request, *args, **kwargs)
#         else:
#             return redirect('todo:index')


class ItemView(View, ContextMixin):
    model = Item
    form_class = ItemForm
    template_name = 'todo/index.html'

    def get(self, request, *args, **kwargs):
        context = self.get_context_data()
        context['form'] = self.form_class()
        print(request)
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = get_object_or_404(get_user_model(), username=request.user)
            user_item = form.save(commit=False)
            user_item.user = user
            user_item.save()
            return self.get(request, *args, **kwargs)
        else:
            context = self.get_context_data()
            context['form'] = form
            return render(request, self.template_name, context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['items'] = Item.objects.filter(user=self.request.user.id)
        return context


class ItemUpdateView(UpdateView):
    form_class = ItemForm
    template_name_suffix = '_update'
    success_url = reverse_lazy('todo:index')

    # TODO: Replace with mixin
    def get(self, request, *args, **kwargs):
        obj = Item.objects.get(pk=kwargs['pk'])
        if request.user.id != obj.user.id:
            return redirect('todo:index')
        return super().get(request, *args, **kwargs)

    def get_object(self):
        print(self.kwargs['pk'])
        return Item.objects.get(pk=self.kwargs['pk'])


class ItemDeleteView(DeleteView):
    success_url = reverse_lazy('todo:index')

    # TODO: Replace with mixin
    def get(self, request, *args, **kwargs):
        obj = Item.objects.get(pk=kwargs['pk'])
        if request.user.id != obj.user.id:
            return redirect('todo:index')
        return super().get(request, *args, **kwargs)

    def get_object(self):
        return Item.objects.get(pk=self.kwargs['pk'])


class UserSignupView(View, ContextMixin):
    template_name = 'registration/signup.html'
    form_class = CustomSignupForm

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, context=self.get_context_data())
    
    def post(self, request, *args, **kwargs):
        form = CustomSignupForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Вы успешно создали аккаунт.', extra_tags='alert alert-success')
            return redirect('login')
        else:
            context = self.get_context_data()
            context['form'] = form
            return render(request, self.template_name, context=context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.form_class()
        return context

django-todo/todo/templates/todo/base.html
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

        <title>Todo, World!</title>
    </head>
    <body>
        <div class="container mt-2">
            <div class="mb-4 border-bottom">
                <h1>Todo-лист на Django</h1>
                {% if request.user %}
                    <p>Пользователь: {{ request.user }} <a href="{% url 'logout' %}" class="float-right">Выйти</a></p>
                {% endif %}
            </div>
            {% block content %}
            {% endblock %}
        </div>
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>

django-todo/todo/templates/todo/index.html
{% extends 'todo/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-12">
            <form class="pb-4 mb-4 border-bottom" method="post">
                {% csrf_token %}
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger mt-4">
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
                <div class="form-group">
                    {{ form.text }}
                    {% for error in form.text.errors %}
                        <div class="alert alert-danger mt-4">
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                </div>
                <input type="submit" class="btn btn-default" value="Создать">
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            {% if items %}
                <ul class="list-group">
                {% for item in items %}
                    <li class="list-group-item">
                        {{ item.text }} <span class="badge badge-dark">{{ item.date }}</span>
                        <div class="float-right">
                            <a href="{% url 'todo:update' item.id %}" class="btn btn-secondary">Редактировать</a>
                            <a href="{% url 'todo:delete' item.id %}" class="btn btn-secondary">Удалить</a>
                        </div>
                    </li>
                {% endfor %}
                </ul>
            {% endif %}
        </div>
    </div>
{% endblock %}

django-todo/todo/templates/todo/item_confirm_delete.html
{% extends 'todo/base.html' %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>Вы уверены, что хотите удалить предмет "{{ object }}"?</p>
        <input type="submit" class="btn btn-default" value="Confirm">
    </form>
{% endblock %}

django-todo/todo/templates/todo/item_update.html
{% extends 'todo/base.html' %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-default" value="Update">
    </form>
{% endblock %}